### ISSUE TITLE
RSS for beers

### ISSUE THREAD

**Issue by OiPenguin** [ErinMorelli/em-beer-manager#3]
This is hardly an issue, rather a feature request. Nevertheless, I noticed when visiting a site using your plugin that I could subscribe to regular post, but what I really wanted was to subscribe to beers/receipes. Wouldn't it be great to enable an RSS-feed for beers so brewers using em-beer-manager could follow each others brewing?

**Comment by ErinMorelli** [comment]
Please see my answer here:
https://wordpress.org/support/topic/rss-for-beers?replies=2#post-8708241
