### ISSUE TITLE
Beers are only added to one Menu even it's set to be in multiple

### ISSUE THREAD

**Issue by omikron** [ErinMorelli/em-beer-manager#8]
In Untappd for business, you can have a beer in multiple Menus.

When syncing with Untappd the beer manager seems to only be placing the beer in the first Menu it finds it in.

**Comment by ErinMorelli** [comment]
Hi @omikron - thanks for reporting this! It is a known current bug with the plugin. I will have a fix for it in the next update!

**Comment by ErinMorelli** [comment]
Hi @omikron - the new version 3.2.0 that just was released should fix the issue with menus not syncing correctly! Please let me know if it does not. Thanks!
